<?php
/**
 * This file is part of the "Meta Leads" package.
 *
 * @package Meta Leads
 * @author Urdhva Tech <contact@urdhva-tech.com>
 * @link https://www.urdhva-tech.com
 * @copyright Urdhva Tech
 * @license As specified in the License Agreement supplied with this package.
 */

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN ut_MetaLeadSubmissions
 */
#[\AllowDynamicProperties]
class ut_MetaLeadSubmissions_sugar extends Basic
{
    public $new_schema = true;
    public $module_dir = 'ut_MetaLeadSubmissions';
    public $object_name = 'ut_MetaLeadSubmissions';
    public $table_name = 'ut_metaleadsubmissions';
    public $importable = false;
    public $disable_row_level_security = true;

    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $description;
    public $deleted;
    public $assigned_user_id;
    public $assigned_user_name;
    public $meta_leadgen_id;
    public $form_id;
    public $form_name;
    public $page_id;
    public $page_name;
    public $platform;
    public $campaign_id;
    public $campaign_name;
    public $ad_id;
    public $adset_id;
    public $submitted_at;
    public $submitted_values;
    public $lead_id;
    public $lead_name;
    public $contact_id;
    public $contact_name;

    public function __construct()
    {
        parent::__construct();
    }

    public function bean_implements($interface)
    {
        switch ($interface) {
            case 'ACL':
                return true;
        }

        return false;
    }
}
