<?php
/**
 * This file is part of the "Meta Leads" package.
 *
 * @package Meta Leads
 * @author Urdhva Tech <contact@urdhva-tech.com>
 * @link https://www.urdhva-tech.com
 * @copyright Urdhva Tech
 * @license As specified in the License Agreement supplied with this package.
 */

$dictionary['ut_MetaLeadSubmissions'] = array(
    'table' => 'ut_metaleadsubmissions',
    'audited' => false,
    'duplicate_merge' => false,
    'inline_edit' => false,
    'massupdate' => false,
    'importable' => false,
    'fields' => array(
        'meta_leadgen_id' => array(
            'name' => 'meta_leadgen_id',
            'vname' => 'LBL_META_LEADGEN_ID',
            'type' => 'varchar',
            'len' => 64,
            'required' => true,
            'audited' => false,
            'reportable' => true,
            'importable' => 'true',
            'massupdate' => false,
            'inline_edit' => false,
        ),
        'form_id' => array(
            'name' => 'form_id',
            'vname' => 'LBL_FORM_ID',
            'type' => 'varchar',
            'len' => 64,
            'reportable' => true,
            'massupdate' => false,
            'inline_edit' => false,
        ),
        'form_name' => array(
            'name' => 'form_name',
            'vname' => 'LBL_FORM_NAME',
            'type' => 'varchar',
            'len' => 255,
            'reportable' => true,
            'massupdate' => false,
            'inline_edit' => false,
        ),
        'page_id' => array(
            'name' => 'page_id',
            'vname' => 'LBL_PAGE_ID',
            'type' => 'varchar',
            'len' => 64,
            'reportable' => true,
            'massupdate' => false,
            'inline_edit' => false,
        ),
        'page_name' => array(
            'name' => 'page_name',
            'vname' => 'LBL_PAGE_NAME',
            'type' => 'varchar',
            'len' => 255,
            'reportable' => true,
            'massupdate' => false,
            'inline_edit' => false,
        ),
        'platform' => array(
            'name' => 'platform',
            'vname' => 'LBL_PLATFORM',
            'type' => 'varchar',
            'len' => 32,
            'reportable' => true,
            'massupdate' => false,
            'inline_edit' => false,
        ),
        'campaign_id' => array(
            'name' => 'campaign_id',
            'vname' => 'LBL_CAMPAIGN_ID',
            'type' => 'varchar',
            'len' => 64,
            'reportable' => true,
            'massupdate' => false,
            'inline_edit' => false,
        ),
        'campaign_name' => array(
            'name' => 'campaign_name',
            'vname' => 'LBL_CAMPAIGN_NAME',
            'type' => 'varchar',
            'len' => 255,
            'reportable' => true,
            'massupdate' => false,
            'inline_edit' => false,
        ),
        'ad_id' => array(
            'name' => 'ad_id',
            'vname' => 'LBL_AD_ID',
            'type' => 'varchar',
            'len' => 64,
            'reportable' => true,
            'massupdate' => false,
        ),
        'adset_id' => array(
            'name' => 'adset_id',
            'vname' => 'LBL_ADSET_ID',
            'type' => 'varchar',
            'len' => 64,
            'reportable' => true,
            'massupdate' => false,
            'inline_edit' => false,
        ),
        'submitted_at' => array(
            'name' => 'submitted_at',
            'vname' => 'LBL_SUBMITTED_AT',
            'type' => 'datetime',
            'reportable' => true,
            'massupdate' => false,
            'inline_edit' => false,
        ),
        'submitted_values' => array(
            'name' => 'submitted_values',
            'vname' => 'LBL_SUBMITTED_VALUES',
            'type' => 'longtext',
            'reportable' => false,
            'massupdate' => false,
            'importable' => false,
            'inline_edit' => false,
        ),
        'lead_id' => array(
            'name' => 'lead_id',
            'vname' => 'LBL_LEAD_ID',
            'type' => 'id',
            'required' => false,
            'reportable' => false,
            'audited' => true,
            'comment' => 'Lead linked to this Meta submission',
            'inline_edit' => false,
        ),
        'lead_name' => array(
            'name' => 'lead_name',
            'rname' => 'name',
            'id_name' => 'lead_id',
            'vname' => 'LBL_LEAD_NAME',
            'type' => 'relate',
            'link' => 'lead_link',
            'table' => 'leads',
            'isnull' => 'true',
            'module' => 'Leads',
            'source' => 'non-db',
            'db_concat_fields' => array(0 => 'first_name', 1 => 'last_name'),
            'inline_edit' => false,
        ),
        'lead_link' => array(
            'name' => 'lead_link',
            'type' => 'link',
            'relationship' => 'lead_ut_metaleadsubmissions',
            'source' => 'non-db',
            'module' => 'Leads',
            'bean_name' => 'Lead',
            'vname' => 'LBL_LEAD_NAME',
            'inline_edit' => false,
        ),
        'contact_id' => array(
            'name' => 'contact_id',
            'vname' => 'LBL_CONTACT_ID',
            'type' => 'id',
            'required' => false,
            'reportable' => false,
            'audited' => true,
            'comment' => 'Contact linked to this Meta submission',
            'inline_edit' => false,
        ),
        'contact_name' => array(
            'name' => 'contact_name',
            'rname' => 'name',
            'id_name' => 'contact_id',
            'vname' => 'LBL_CONTACT_NAME',
            'type' => 'relate',
            'link' => 'contact_link',
            'table' => 'contacts',
            'isnull' => 'true',
            'module' => 'Contacts',
            'source' => 'non-db',
            'db_concat_fields' => array(0 => 'first_name', 1 => 'last_name'),
            'inline_edit' => false,
        ),
        'contact_link' => array(
            'name' => 'contact_link',
            'type' => 'link',
            'relationship' => 'contact_ut_metaleadsubmissions',
            'source' => 'non-db',
            'module' => 'Contacts',
            'bean_name' => 'Contact',
            'vname' => 'LBL_CONTACT_NAME',
            'inline_edit' => false,
        ),
    ),
    'relationships' => array(
        'lead_ut_metaleadsubmissions' => array(
            'lhs_module' => 'Leads',
            'lhs_table' => 'leads',
            'lhs_key' => 'id',
            'rhs_module' => 'ut_MetaLeadSubmissions',
            'rhs_table' => 'ut_metaleadsubmissions',
            'rhs_key' => 'lead_id',
            'relationship_type' => 'one-to-many',
        ),
        'contact_ut_metaleadsubmissions' => array(
            'lhs_module' => 'Contacts',
            'lhs_table' => 'contacts',
            'lhs_key' => 'id',
            'rhs_module' => 'ut_MetaLeadSubmissions',
            'rhs_table' => 'ut_metaleadsubmissions',
            'rhs_key' => 'contact_id',
            'relationship_type' => 'one-to-many',
        ),
    ),
    'indices' => array(
        array(
            'name' => 'idx_ut_mls_leadgen',
            'type' => 'index',
            'fields' => array('meta_leadgen_id', 'deleted'),
        ),
        array(
            'name' => 'idx_ut_mls_lead',
            'type' => 'index',
            'fields' => array('lead_id'),
        ),
        array(
            'name' => 'idx_ut_mls_contact',
            'type' => 'index',
            'fields' => array('contact_id'),
        ),
    ),
    'optimistic_locking' => true,
);

if (!class_exists('VardefManager')) {
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('ut_MetaLeadSubmissions', 'ut_MetaLeadSubmissions', array('basic', 'assignable'));
