<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

$dictionary['SummarizationGai'] = [
    'table' => 'summarization_gai',
    'archive' => false,
    'audited' => false,
    'activity_enabled' => false,
    'reassignable' => false,
    'duplicate_merge' => false,
    'unified_search' => false,
    'unified_search_default_enabled' => false,
    'fields' => [
        'id' => [
            'name' => 'id',
            'vname' => 'LBL_ID',
            'type' => 'id',
            'required' => true,
            'reportable' => false,
            'duplicate_on_record_copy' => 'no',
            'comment' => 'Unique identifier',
            'mandatory_fetch' => true,
        ],
        'date_entered' => [
            'name' => 'date_entered',
            'vname' => 'LBL_DATE_ENTERED',
            'type' => 'datetime',
            'group' => 'created_by_name',
            'comment' => 'Date record created',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
            'studio' => [
                'portaleditview' => false,
            ],
            'duplicate_on_record_copy' => 'no',
            'readonly' => true,
            'massupdate' => false,
            'full_text_search' => [
                'enabled' => true,
                'searchable' => false,
            ],
            'hideacl' => true,
        ],
        'date_modified' => [
            'name' => 'date_modified',
            'vname' => 'LBL_DATE_MODIFIED',
            'type' => 'datetime',
            'group' => 'modified_by_name',
            'comment' => 'Date record last modified',
            'enable_range_search' => true,
            'full_text_search' => [
                'enabled' => true,
                'searchable' => false,
                'sortable' => true,
            ],
            'studio' => [
                'portaleditview' => false,
            ],
            'options' => 'date_range_search_dom',
            'duplicate_on_record_copy' => 'no',
            'readonly' => true,
            'massupdate' => false,
            'hideacl' => true,
        ],
        'last_sync_date' => [
            'name' => 'last_sync_date',
            'vname' => 'LBL_LAST_SYNC_DATE',
            'type' => 'datetime',
            'comment' => 'Date record last sync with GAI service',
            'enable_range_search' => true,
            'full_text_search' => [
                'enabled' => true,
                'searchable' => false,
                'sortable' => true,
            ],
            'studio' => [
                'portaleditview' => false,
            ],
            'options' => 'date_range_search_dom',
            'duplicate_on_record_copy' => 'no',
            'readonly' => true,
            'reportable' => false,
            'massupdate' => false,
            'hideacl' => true,
        ],
        'deleted' => [
            'name' => 'deleted',
            'vname' => 'LBL_DELETED',
            'type' => 'bool',
            'default' => '0',
            'reportable' => false,
            'duplicate_on_record_copy' => 'no',
            'comment' => 'Record deletion indicator',
        ],
        'is_translate' => [
            'name' => 'is_translate',
            'vname' => 'LBL_IS_TRANSLATE',
            'type' => 'bool',
            'default' => '0',
            'isnull' => false,
            'reportable' => false,
            'duplicate_on_record_copy' => 'no',
            'comment' => 'Used to determin if it is the original summarization or a translation of the summarization',
            'hideacl' => true,
        ],
        'parent_id' => [
            'required' => true,
            'name' => 'parent_id',
            'vname' => 'LBL_PARENT_ID',
            'reportable' => false,
            'type' => 'id',
        ],
        'parent_module' => [
            'required' => true,
            'name' => 'parent_module',
            'vname' => 'LBL_PARENT_MODULE',
            'type' => 'varchar',
            'massupdate' => false,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'false',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'merge_filter' => 'disabled',
            'reportable' => false,
            'hideacl' => true,
        ],
        'eval_id' => [
            'required' => false,
            'name' => 'eval_id',
            'reportable' => false,
            'vname' => 'LBL_EVAL_ID',
            'type' => 'id',
        ],
        'language' => [
            'required' => true,
            'name' => 'language',
            'vname' => 'LBL_LANGUAGE',
            'type' => 'enum',
            'massupdate' => false,
            'default' => 'en_us',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'false',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'merge_filter' => 'disabled',
            'reportable' => true,
            'options' => 'available_language_dom',
            'hideacl' => true,
        ],
        'prompt_tokens' => [
            'required' => true,
            'name' => 'prompt_tokens',
            'vname' => 'LBL_PROMPT_TOKENS',
            'type' => 'varchar',
            'massupdate' => false,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'false',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => false,
            'merge_filter' => 'disabled',
            'hideacl' => true,
        ],
        'completion_tokens' => [
            'required' => true,
            'name' => 'completion_tokens',
            'vname' => 'LBL_USED_TOKENS',
            'type' => 'varchar',
            'massupdate' => false,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'false',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => false,
            'merge_filter' => 'disabled',
            'hideacl' => true,
        ],
        'hash' => [
            'required' => true,
            'name' => 'hash',
            'vname' => 'LBL_HASH',
            'type' => 'varchar',
            'massupdate' => false,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'false',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => false,
            'merge_filter' => 'disabled',
            'len' => '64',
            'size' => '64',
            'hideacl' => true,
        ],
        'status' => [
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'varchar',
            'massupdate' => false,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'false',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'merge_filter' => 'disabled',
            'len' => '64',
            'size' => '64',
            'hideacl' => true,
        ],
        'sentiment' => [
            'required' => true,
            'name' => 'sentiment',
            'vname' => 'LBL_SENTIMENT',
            'type' => 'enum',
            'options' => 'gai_sentiment_enums',
            'default' => '',
            'len' => '255',
            'merge_filter' => 'disabled',
            'importable' => 'false',
            'audited' => true,
            'massupdate' => false,
            'hidemassupdate' => true,
            'comments' => 'Indication of progression towards closure',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => 1,
            'calculated' => false,
            'dependency' => false,
            'reportable' => true,
            'hideacl' => true,
        ],
        'summary' => [
            'name' => 'summary',
            'vname' => 'LBL_SUMMARY',
            'type' => 'gai_summary',
            'custom_type' => 'text',
            'dbType' => 'longtext',
            'help' => 'Summarization',
            'hideacl' => true,
        ],
        'needed_followup' => [
            'name' => 'needed_followup',
            'vname' => 'LBL_NEEDED_FOLLOWUP',
            'type' => 'gai_needed_followup',
            'custom_type' => 'text',
            'dbType' => 'longtext',
            'help' => 'Needed followup',
            'reportable' => true,
            'hideacl' => true,
        ],
        'engaged_contacts' => [
            'name' => 'engaged_contacts',
            'vname' => 'LBL_ENGAGED_CONTACTS',
            'type' => 'gai_engaged_contacts',
            'custom_type' => 'text',
            'dbType' => 'longtext',
            'help' => 'Engaged Contacts',
            'reportable' => true,
            'hideacl' => true,
        ],
        'participants' => [
            'name' => 'participants',
            'vname' => 'LBL_PARTICIPANTS',
            'type' => 'text',
            'help' => 'Participants',
            'reportable' => false,
            'hideacl' => true,
        ],
        'sentiment_actions' => [
            'name' => 'sentiment_actions',
            'vname' => 'LBL_SENTIMENTS_ACTIONS',
            'type' => 'text',
            'help' => 'Actions contributing to sentiment',
            'reportable' => false,
            'hideacl' => true,
        ],
        'suggested_next_steps' => [
            'name' => 'suggested_next_steps',
            'vname' => 'LBL_NEXT_STEPS',
            'type' => 'gai_summary',
            'custom_type' => 'text',
            'dbType' => 'longtext',
            'help' => 'Suggested next steps',
            'reportable' => true,
            'hideacl' => true,
        ],
        'error_message' => [
            'name' => 'error_message',
            'vname' => 'LBL_ERROR_MESSAGE',
            'type' => 'text',
            'help' => 'Summarization Error Message',
            'hideacl' => true,
        ],
        'opportunities_summz_gai' => [
            'name' => 'opportunities_summz_gai',
            'type' => 'link',
            'relationship' => 'opportunities_summz_gai',
            'source' => 'non-db',
            'module' => 'Opportunities',
            'bean_name' => 'Opportunity',
            'side' => 'right',
            'vname' => 'LBL_OPPORTUNITIES_SUMMZ_GAI_REL_FROM_GAI_TITLE',
            'id_name' => 'opportunities_summz_gaiopportunities_ida',
            'link-type' => 'one',
        ],
        'opportunities_summz_gai_name' => [
            'name' => 'opportunities_summz_gai_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_OPPORTUNITIES_SUMMZ_GAI_REL_FROM_OPP_TITLE',
            'save' => true,
            'id_name' => 'opportunities_summz_gaiopportunities_ida',
            'link' => 'opportunities_summz_gai',
            'table' => 'opportunities',
            'module' => 'Opportunities',
            'rname' => 'name',
            'hideacl' => true,
        ],
        'opportunities_summz_gaiopportunities_ida' => [
            'name' => 'opportunities_summz_gaiopportunities_ida',
            'type' => 'id',
            'source' => 'non-db',
            'vname' => 'LBL_OPPORTUNITIES_SUMMZ_GAI_REL_FROM_OPP_TITLE_ID',
            'id_name' => 'opportunities_summz_gaiopportunities_ida',
            'link' => 'opportunities_summz_gai',
            'table' => 'opportunities',
            'module' => 'Opportunities',
            'rname' => 'id',
            'reportable' => false,
            'side' => 'right',
            'massupdate' => false,
            'duplicate_merge' => 'disabled',
            'hideacl' => true,
        ],
        'cases_summz_gai' => [
            'name' => 'cases_summz_gai',
            'type' => 'link',
            'relationship' => 'cases_summz_gai',
            'source' => 'non-db',
            'module' => 'Cases',
            'bean_name' => 'Case',
            'side' => 'right',
            'vname' => 'LBL_CASES_SUMMZ_GAI_REL_FROM_GAI_TITLE',
            'id_name' => 'cases_summz_gaicases_ida',
            'link-type' => 'one',
        ],
        'cases_summz_gai_name' => [
            'name' => 'cases_summz_gai_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_CASES_SUMMZ_GAI_REL_FROM_CASES_TITLE',
            'save' => true,
            'id_name' => 'cases_summz_gaicases_ida',
            'link' => 'cases_summz_gai',
            'table' => 'cases',
            'module' => 'Cases',
            'rname' => 'name',
            'hideacl' => true,
        ],
        'cases_summz_gaicases_ida' => [
            'name' => 'cases_summz_gaicases_ida',
            'type' => 'id',
            'source' => 'non-db',
            'vname' => 'LBL_CASES_SUMMZ_GAI_REL_FROM_OPP_TITLE_ID',
            'id_name' => 'cases_summz_gaicases_ida',
            'link' => 'cases_summz_gai',
            'table' => 'cases',
            'module' => 'Cases',
            'rname' => 'id',
            'reportable' => false,
            'side' => 'right',
            'massupdate' => false,
            'duplicate_merge' => 'disabled',
            'hideacl' => true,
        ],
        'accounts_summz_gai' => [
            'name' => 'accounts_summz_gai',
            'type' => 'link',
            'relationship' => 'accounts_summz_gai',
            'source' => 'non-db',
            'module' => 'Accounts',
            'bean_name' => 'Account',
            'side' => 'right',
            'vname' => 'LBL_ACCOUNTS_SUMMZ_GAI_REL_FROM_GAI_TITLE',
            'id_name' => 'accounts_summz_gaiaccounts_ida',
            'link-type' => 'one',
        ],
        'accounts_summz_gai_name' => [
            'name' => 'accounts_summz_gai_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_ACCOUNTS_SUMMZ_GAI_REL_FROM_ACC_TITLE',
            'save' => true,
            'id_name' => 'accounts_summz_gaiaccounts_ida',
            'link' => 'accounts_summz_gai',
            'table' => 'accounts',
            'module' => 'Accounts',
            'rname' => 'name',
            'hideacl' => true,
        ],
        'accounts_summz_gaiaccounts_ida' => [
            'name' => 'accounts_summz_gaiaccounts_ida',
            'type' => 'id',
            'source' => 'non-db',
            'vname' => 'LBL_ACCOUNTS_SUMMZ_GAI_REL_FROM_OPP_TITLE_ID',
            'id_name' => 'accounts_summz_gaiaccounts_ida',
            'link' => 'accounts_summz_gai',
            'table' => 'accounts',
            'module' => 'Accounts',
            'rname' => 'id',
            'reportable' => false,
            'side' => 'right',
            'massupdate' => false,
            'duplicate_merge' => 'disabled',
            'hideacl' => true,
        ],
    ],
    'indices' => [
        'id' => [
            'name' => 'idx_sumz_pk',
            'type' => 'primary',
            'fields' => ['id'],
        ],
        'date_modified' => [
            'name' => 'idx_sumz_del_d_m',
            'type' => 'index',
            'fields' => ['deleted', 'date_modified', 'id'],
        ],
        'deleted' => [
            'name' => 'idx_sumz_id_del',
            'type' => 'index',
            'fields' => ['id', 'deleted'],
        ],
        'date_entered' => [
            'name' => 'idx_sumz_del_d_e',
            'type' => 'index',
            'fields' => ['deleted', 'date_entered', 'id'],
        ],
        'status' => [
            'name' => 'idx_sumz_status',
            'type' => 'index',
            'fields' => ['status'],
        ],
        'parent_id' => [
            'name' => 'idx_sumz_parent_id',
            'type' => 'index',
            'fields' => ['parent_id'],
        ],
        'parent_module' => [
            'name' => 'idx_sumz_parent_module',
            'type' => 'index',
            'fields' => ['parent_module'],
        ],
        'sentiment' => [
            'name' => 'idx_sumz_sentiment',
            'type' => 'index',
            'fields' => ['sentiment'],
        ],
        'eval_id' => [
            'name' => 'idx_sumz_eval_id',
            'type' => 'index',
            'fields' => ['eval_id', 'deleted'],
        ],
        'language' => [
            'name' => 'idx_sumz_language',
            'type' => 'index',
            'fields' => ['language'],
        ],
        'record_status' => [
            'name' => 'idx_sumz_record_status',
            'type' => 'index',
            'fields' => ['parent_id', 'parent_module', 'status'],
        ],
        'record_is_translate_exists' => [
            'name' => 'idx_sumz_record_is_translate_exists',
            'type' => 'index',
            'fields' => ['parent_id', 'parent_module', 'is_translate'],
        ],
        'record_exist' => [
            'name' => 'idx_sumz_record_exist',
            'type' => 'index',
            'fields' => ['parent_id', 'parent_module', 'hash'],
        ],
        'saved_summary_exist' => [
            'name' => 'idx_saved_summary_exist',
            'type' => 'index',
            'fields' => ['parent_id', 'parent_module'],
        ],
        'saved_language_summary_exist' => [
            'name' => 'idx_language_saved_summary_exist',
            'type' => 'index',
            'fields' => ['parent_id', 'parent_module', 'language'],
        ],
        'idx_record_status_language_exists' => [
            'name' => 'idx_record_status_language_exists',
            'type' => 'index',
            'fields' => ['parent_id', 'parent_module', 'status', 'language', 'deleted', 'date_modified'],
        ],
        'idx_translate_summary' => [
            'name'   => 'idx_summarization_optimized',
            'type'   => 'index',
            'fields' => ['parent_id', 'parent_module', 'deleted', 'is_translate', 'date_modified', 'id'],
        ],
        'record_status_is_translate_exists' => [
            'name' => 'idx_record_status_is_translate_exists',
            'type' => 'index',
            'fields' => ['parent_id', 'parent_module', 'status', 'is_translate', 'deleted', 'date_modified', 'id'],
        ],
        'record_exist_lang' => [
            'name' => 'idx_sumz_record_exist_lang',
            'type' => 'index',
            'fields' => ['parent_id', 'parent_module', 'hash', 'language'],
        ],
        'is_summz_translate_exist_gai' => [
            'name' => 'idx_is_summz_translate_exist_gai',
            'type' => 'index',
            'fields' => ['parent_id', 'parent_module', 'is_translate', 'hash'],
        ],
        'record_validation' => [
            'name' => 'idx_sumz_record_validation',
            'type' => 'index',
            'fields' => ['parent_id', 'parent_module', 'hash', 'status'],
        ],
        'idx_sumz_record_status_deleted_id' => [
            'name' => 'idx_sumz_record_status_deleted_id',
            'type' => 'index',
            'fields' => ['parent_id', 'parent_module', 'status', 'deleted', 'id'],
        ],
        'idx_sumz_record_status_deleted_id_language' => [
            'name' => 'idx_sumz_record_status_deleted_id_language',
            'type' => 'index',
            'fields' => ['parent_id', 'parent_module', 'status', 'deleted', 'id', 'language'],
        ],
        'last_sync_date_parent_id_type' => [
            'name' => 'idx_last_sync_date_parent_id_type',
            'type' => 'index',
            'fields' => ['last_sync_date', 'parent_id', 'parent_module'],
        ],
        'idx_summarization_retrieve_old' => [
            'name'   => 'idx_summarization_retrieve_old',
            'type'   => 'index',
            'fields' => ['parent_id', 'parent_module', 'status', 'deleted', 'language', 'date_entered', 'id'],
        ],
    ],
    'relationships' => [],
    'optimistic_locking' => true,
    'portal_visibility' => [],
    'ignore_templates' => [
        'integrate_fields',
        'default',
    ],
    'uses' => [],
];

VardefManager::createVardef('SummarizationGai', 'SummarizationGai');
